project_id = "pdyywievbtdhtxylylln"

[functions.send-announcement-email]
verify_jwt = false

[functions.send-login-code]
verify_jwt = false

[functions.delete-firebase-user]
verify_jwt = false

[functions.send-credentials-email]
verify_jwt = false